### PR TITLE
formated all files in proper c++ format

### PR DESCRIPTION
**Pull request by CCAtAlvis**
i.e. replace printf() with cout and scanf() with cin
changed nested if logic to nested if switch logic

### CODE REVIEW

**Comment by nerdyninja** [comment]
Thanks for the hardwork. But, scanf and printf works faster on Online Judges as compared to cin and cout.
You might be using g++ -std=c++11, which is your choice. 
PS: Try for some new solutions 👍

**Comment by CCAtAlvis** [comment]
Wasnt that hardwork :). Yes scanf and printf are pretty fast compared to cin and cout but then most of programs arent using anything special of c++, so you could just make them c programs (that would be even faster i think). I can try for new solutions but there are no problem statements with them (except for one).

**Comment by nerdyninja** [comment]
C doesn't support STLs. Life will be too tough with C in CP.

**Comment by CCAtAlvis** [comment]
ok got you. and what about the nested if logic to nested if switch logic and also you have nested ifs,all if contain only 1 condition that can be merged in single if.

**Pull request closed without merging**
